notify = true

[theme]
primary = "#c5c9c5"
secondary = "#737c73"
title = "#7fb4ca"
playing = "#8a9a7b"
playing_selected = "#8a9a7b"
playing_bg = "#2d4f67"
highlight = "#c5c9c5"
highlight_bg = "#2d4f67"
error = "#c4746f"
error_bg = "#181616"
statusbar = "#c5c9c5"
statusbar_progress = "#7fb4ca"
statusbar_bg = "#1d1c19"
cmdline = "#c5c9c5"
cmdline_bg = "#1d1c19"

[keybindings]
"Space" = "playpause"
