notify = true

[theme]
primary = "#cdd6f4"
secondary = "#6c7086"
title = "#89b4fa"
playing = "#a6e3a1"
playing_selected = "#a6e3a1"
playing_bg = "#313244"
highlight = "#cdd6f4"
highlight_bg = "#45475a"
error = "#f38ba8"
error_bg = "#1e1e2e"
statusbar = "#cdd6f4"
statusbar_progress = "#89b4fa"
statusbar_bg = "#181825"
cmdline = "#cdd6f4"
cmdline_bg = "#181825"

[keybindings]
"Space" = "playpause"
